#!/usr/bin/env python

import datetime
import re
import urllib2
from lxml import etree
from popolo import Popolo
from popolo.utils import new_id

parser = etree.ETCompatXMLParser()
etree.set_default_parser(parser)

data = Popolo()


def canon_name(n):
    n = re.sub(' St\. +', ' St ', n)
    n = re.sub('^The ', '', n)
    n = re.sub(' De ', ' de ', n)
    n = re.sub('Lord (Archb|B)ishop ', r'\1ishop ', n)
    return n


lord_match = re.compile('^([^\s]*)\s+(.*?)(?:\s+of\s+(.*))?$')

party_map = {
    'Liberal Democrats': 'liberal-democrat',
    'Conservative': 'conservative',
    'Crossbench': 'crossbench',
    'Labour': 'labour',
    'Green Party': 'green',
    'Bishops': 'bishop',
    'Democratic Unionist Party': 'dup',
    'Non-affiliated': 'non-affiliated'
}

type_map = {
    'Life peer': 'L',
    'Excepted Hereditary': 'HP',
    'Bishops': 'B'
}


def construct_name(member):
    given_name = member.find('BasicDetails/GivenForename').text
    middle_names = member.find('BasicDetails/GivenMiddleNames').text
    surname = member.find('BasicDetails/GivenSurname').text
    title_parts = lord_match.search(member.find('DisplayAs').text)
    prefix = title_parts.group(1)
    lordname = title_parts.group(2)
    lordof = title_parts.group(3) or ''
    if prefix == 'The' and lordname in ('Lord Bishop', 'Lord Archbishop'):
        prefix = lordname.replace('Lord ', '')
        lordname = ''
    name = {
        'given_name': given_name,
        'honorific_prefix': prefix,
        'lordname': lordname,
        'lordofname': lordof,
        'lordofname_full': '',
        'county': '',
        'note': 'Main',
    }
    if middle_names:
        name['additional_name'] = middle_names
    if surname and surname != lordname:
        name['surname'] = surname
    return name


def construct_person(member, person_id, name):
    ids = [
        {
            'scheme': 'pims_id',
            'identifier': member.attrib['Pims_Id']
        },
        {
            'scheme': 'datadotparl_id',
            'identifier': member.attrib['Member_Id']
        }
    ]
    person = {
        'id': person_id,
        'identifiers': ids,
        'other_names': [name]
    }
    return person

def construct_membership(member, person_id, lord_id):
    lord_type = type_map[member.find('MemberFrom').text]
    party = party_map[member.find('Party').text]
    start_date = re.sub('T.*$', '', member.find('HouseStartDate').text)
    membership = {
        'id': lord_id,
        'identifiers': [{
            'identifier': lord_type,
            'scheme': 'peeragetype'
        }],
        'label': 'Peer',
        'on_behalf_of_id': party,
        'organization_id': 'house-of-lords',
        'person_id': person_id,
        'role': 'Peer',
        'start_date': start_date
    }
    if not membership['start_date'] or not membership['on_behalf_of_id']:
        print "Missing start date or party!"
        sys.exit()
    return membership


LORDS_URL = 'http://data.parliament.uk/membersdataplatform/services/mnis/members/query/house=Lords/BasicDetails'
parl_members = etree.parse(urllib2.urlopen(LORDS_URL)).getroot()

new_people = False
person_id = data.max_person_id()
for member in parl_members:
    end_date = member.find('HouseEndDate').text or ''
    end_date = end_date.replace('T00:00:00', '')
    if end_date and end_date < '1999-11-12':
        continue
    name = canon_name(member.find('DisplayAs').text)
    person = data.get_person(id=member.attrib['Member_Id'], scheme='datadotparl_id')
    if not person:
        person_id = new_id(person_id)
        lord_id = new_id(data.max_lord_id())
        print "{} is a new Lord, person ID {}, lord ID {}".format(name, person_id, lord_id)

        name = construct_name(member)
        person = construct_person(member, person_id, name)
        membership = construct_membership(member, person_id, lord_id)

        data.add_person(person)
        data.add_membership(membership)
        new_people = True
    elif data.names[person['id']] == name:
        # Same lord name, assume already got them
        continue
    else:
        lord_id = new_id(data.max_lord_id())
        print "{} is a new Lord already in the system, person ID {}, lord ID {}".format(name, person['id'], lord_id)

        name = construct_name(member)
        membership = construct_membership(member, person['id'], lord_id)
        names = [n for n in person['other_names'] if n['note'] == 'Main']
        latest_name = sorted(names, key=lambda x: x.get('start_date', '0000-00-00'), reverse=True)[0]
        day_before = datetime.datetime.strptime(membership['start_date'], '%Y-%m-%d') - datetime.timedelta(days=1)
        latest_name['end_date'] = day_before.date().isoformat()
        name['start_date'] = membership['start_date']
        person['other_names'].append(name)

        data.add_membership(membership)
        new_people = True

if new_people:
    data.dump()
