#!/bin/bash
set -e
# set -x # debug

# Change watcher, loads pages often and if they have changed either
# emails someone, or keeps a copy of # each version.

source ~/parlparse/scripts/consts

# Add any new files
cd ~/parldata/cmpages/chgpages
svn -q add */*.html 2>&1 | grep -v "is already under version control" && echo -n

# Check for updates to minister pages etc.
cd ~/parlparse/pyscraper
./lazyrunall.py scrape chgpages

# Regenerate minister pages file
#./lazyrunall.py parse chgpages
