#!/bin/bash
# Jobs that need running daily, that aren't with urgency dependent on new stuff
# from Hansard

cd ~/parlparse

# update the parlparse directory
git pull -q

# Update register of members interests
cd ~/parlparse
poetry run python -m pyscraper.regmem download-latest-register --chamber commons --quiet
poetry run python -m pyscraper.regmem download-latest-register --chamber scotland --quiet
poetry run python -m pyscraper.regmem download-latest-register --chamber senedd --quiet
poetry run python -m pyscraper.regmem download-latest-register --chamber ni --quiet
poetry run python -m pyscraper.regmem download-latest-register --chamber lords --quiet

# update commons EDMs
poetry run python -m pyscraper.edms update --quiet

# Update committee info file
poetry run python -m pyscraper.committees all --quiet
