#!/bin/bash
# Jobs that need running daily, that aren't with urgency dependent on new stuff
# from Hansard

source ~/parlparse/scripts/consts

# Update register of members interests
cd ~/parlparse
poetry run python -m pyscraper.regmem download-all-registers --chamber commons --no-progress

# Get updated members list all-members.xml, in case it changed
#cd ~/parlparse/members
#git pull --rebase

YEAR=`date +%Y`

cd ~/parlparse/scripts
./fetch-pw-json

# Check for new people
./add-new-mlas
./add-new-lords

