#!/bin/bash

set -e

if [[ "$1" == "--verbose" ]]; then
    set -x  # for debugging, prints each line before executing it
fi

# Scripts that update data *in* parlparse. Run in github. 

root_dir=$(dirname $(dirname $(readlink -f $0)))

source $root_dir/scripts/consts

cd $root_dir
# Check for new people
scripts/add-new-mlas  $1
scripts/add-new-lords $1

# run data.parliament scrapers
# run data.parliament scrapers
cd $root_dir/scripts/datadotparl
./crawl-members $1
./update-members $1

# fetch details of scottish ministers
cd $root_dir
scripts/fetch_scottish_ministers.py

# Run member scrapers
# TODO: add more, write to temp file, check errors
cd $root_dir/rawdata
curl -s "https://en.wikipedia.org/wiki/Members_of_the_House_of_Lords" > Members_of_the_House_of_Lords
curl -s "https://en.wikipedia.org/wiki/List_of_MPs_elected_in_the_United_Kingdom_general_election,_2015" > Members_of_the_House_of_Commons_2015
curl -s "https://en.wikipedia.org/wiki/MPs_elected_in_the_UK_general_election,_2010" > Members_of_the_House_of_Commons_2010
curl -s "https://en.wikipedia.org/wiki/MPs_elected_in_the_UK_general_election,_2005" > Members_of_the_House_of_Commons_2005
curl -s "https://en.wikipedia.org/wiki/MPs_elected_in_the_UK_general_election,_2001" > Members_of_the_House_of_Commons_2001
curl -s "https://en.wikipedia.org/wiki/MPs_elected_in_the_UK_general_election,_1997" > Members_of_the_House_of_Commons_1997
curl -s "https://en.wikipedia.org/wiki/2nd_Northern_Ireland_Assembly" > Members_of_the_NIA_2003
curl -s "https://en.wikipedia.org/wiki/3rd_Northern_Ireland_Assembly" > Members_of_the_NIA_2007
curl -s "https://en.wikipedia.org/wiki/4th_Northern_Ireland_Assembly" > Members_of_the_NIA_2011
curl -s "https://en.wikipedia.org/wiki/5th_Northern_Ireland_Assembly" > Members_of_the_NIA_2016
curl -s "https://en.wikipedia.org/wiki/6th_Northern_Ireland_Assembly" > Members_of_the_NIA_2017
curl -s 'https://en.wikipedia.org/wiki/7th_Northern_Ireland_Assembly' > Members_of_the_NIA_2022
curl -s "https://en.wikipedia.org/wiki/1st_Scottish_Parliament" > Members_of_the_1st_Scottish_Parliament
curl -s "https://en.wikipedia.org/wiki/2nd_Scottish_Parliament" > Members_of_the_2nd_Scottish_Parliament
curl -s "https://en.wikipedia.org/wiki/3rd_Scottish_Parliament" > Members_of_the_3rd_Scottish_Parliament
curl -s "https://en.wikipedia.org/wiki/4th_Scottish_Parliament" > Members_of_the_4th_Scottish_Parliament
curl -s "https://en.wikipedia.org/wiki/5th_Scottish_Parliament" > Members_of_the_5th_Scottish_Parliament
curl -s "https://en.wikipedia.org/wiki/6th_Scottish_Parliament" > Members_of_the_6th_Scottish_Parliament


cd $root_dir/members
./wikipedia-lords.py > wikipedia-lords.xml
./wikipedia-commons.py > wikipedia-commons.xml
# ./bbcconv.py > bbc-links.xml 
cd $root_dir/pyscraper
ni/wikipedia-mla.py > ../members/wikipedia-mla.xml
sp/wikipedia-msp.py > ../members/wikipedia-msp.xml

# check the new data hasn't added data validation issues
cd $root_dir
mysoc-validator popolo validate members/people.json