#!/usr/bin/env python

from popolo import Popolo
data = Popolo()

mships = data.memberships.in_org('house-of-commons').current()
assert len(mships) == 650
for mship in mships:
    mship['end_date'] = '2019-11-06'
    mship['end_reason'] = 'dissolution'

data.dump()
