#!/usr/bin/env python

from popolo import Popolo
data = Popolo()

mships = data.memberships.in_org('scottish-parliament').current()
assert len(mships) == 129
for mship in mships:
    mship['end_date'] = '2021-05-05'
    mship['end_reason'] = 'dissolution'

data.dump()
