#!/usr/bin/env python

import argparse
import json
import os
import sys
import tempfile
from popolo import Popolo


def edit_file(edit_data):
    fp = tempfile.NamedTemporaryFile(delete=False)
    json.dump(edit_data, fp, sort_keys=True, indent=2)
    fp.close()
    try:
        while True:
            os.system('vim "%s"' % fp.name)
            with open(fp.name) as f:
                try:
                    new_edit_data = json.load(f)
                    break
                except ValueError as e:
                    print "Bad JSON: %s" % e
                    raw_input("Press Enter to continue...")
    finally:
        os.remove(fp.name)
    return new_edit_data


parser = argparse.ArgumentParser()
parser.add_argument('--name', required=True)
ARGS = parser.parse_args()

data = Popolo()

person = data.get_person(name=ARGS.name)
if len(person) != 1:
    raise Exception('Did not get one person: %s' % person)
person = person[0]

mships = data.memberships.of_person(person['id'])

edit_data = {
    'max_lord_id': data.max_lord_id(),
    'person': person,
    'memberships': list(mships),
}
new_edit_data = edit_file(edit_data)

if edit_data == new_edit_data:
    sys.exit()

data.persons[person['id']].update(new_edit_data['person'])
edit_mships = {m['id']: m for m in new_edit_data['memberships']}
for m in data.memberships:
    if m['id'] in edit_mships:
        m.update(edit_mships[m['id']])
        del edit_mships[m['id']]

for m in edit_mships.values():
    data.add_membership(m)

data.dump()
