#!/usr/bin/env python

from popolo import Popolo
data = Popolo()

mships = data.memberships.in_org('northern-ireland-assembly').current()
assert len(mships) == 108
for mship in mships:
    mship['end_date'] = '2017-01-26'
    mship['end_reason'] = 'dissolved'

data.dump()
