#!/usr/bin/env python3

import argparse
from popolo import Popolo
data = Popolo()

parser = argparse.ArgumentParser(description='End all current members in a body')
parser.add_argument('--body', required=True, choices=data.houses)
parser.add_argument('--check', required=True, type=int)
parser.add_argument('--end-date', required=True)
args = parser.parse_args()

mships = data.memberships.in_org(args.body).current()
assert len(mships) == args.check, len(mships)
for mship in mships:
    mship['end_date'] = args.end_date
    mship['end_reason'] = 'dissolution'

data.dump()
