#!/usr/bin/env python

from popolo import Popolo
data = Popolo()

mships = data.memberships.in_org('house-of-commons').current()
# only 649 as the Manchester Gorton By-election was outstanding
assert len(mships) == 649
for mship in mships:
    mship['end_date'] = '2017-05-04'
    mship['end_reason'] = 'dissolved'

data.dump()
