#!/usr/bin/env python3
#
# End a current membership

import datetime
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--name', required=True)
parser.add_argument('--date', required=True)
parser.add_argument('--reason', required=True)
ARGS = parser.parse_args()
try:
    datetime.datetime.strptime(ARGS.date, '%Y-%m-%d')
except ValueError:
    parser.error('Date in wrong format')

from popolo import Popolo
data = Popolo()

person = data.get_person(name=ARGS.name)
if len(person) != 1:
    raise Exception('Did not get one person: %s' % person)
person = person[0]

mships = data.memberships.of_person(person['id'])
mships_current = mships.current()
if not len(mships_current):
    raise Exception('No current membership, previous ones: %s' % mships)
elif len(mships_current) > 1:
    raise Exception('Multiple current memberships: %s' % mships_current)

mship = mships_current.memberships[0]
mship['end_date'] = ARGS.date
mship['end_reason'] = ARGS.reason

data.dump()
