#!/bin/bash

# Lords update

FROMDATE=$1
TODATE=$2
# $3 is extra flags to pass through
# echo "updatedaterange from $1 to $2"

# Run XML-generating scraper from Public Whip, getting new files from network
# and parsing lords into pages
cd ~/parlparse/pyscraper
./lazyrunall.py --from=$FROMDATE --to=$TODATE scrape lords
# We do these on separate lines, so if one fails, others still run
./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse lords

