#!/bin/bash

if [ "$1" == "0" ]
then
    RET=0
else
    RET=1
fi

# Tell TheyWorkForYou to update. The weird XFF header is to work around an
# apparent bug in mod_rpaf whereby persistent varnish connections to Apache are
# losing the actual source IP after the first request and being rejected.
PRODSCRIPT=ukparse-morning-update-done.cgi
curl -s -H 'X-Forwarded-For: 127.0.0.1' https://www.theyworkforyou.com/internal/$PRODSCRIPT/$RET >/dev/null &

# Update division archive for Public Whip to feed from
`dirname $0`/divisionextractor.pl

# tell Public Whip to update
PRODSCRIPT=ukparse-morning-update-done.cgi
curl -s http://www.publicwhip.org.uk/$PRODSCRIPT >/dev/null &
