#!/bin/bash

# Parsing

FROMDATE=$1
LORDFROMDATE=$2
TODATE=$3
RET=0
# $4 is extra flags to pass through
# echo "updatedaterange from $1/$2 to $3"

# Run parsers to convert various HTML into XML
cd ~/parlparse/pyscraper
# We do these on separate lines, so if one fails, others still run
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse debates || RET=1
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse wrans || RET=1
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse westminhall || RET=1
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse wms || RET=1
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse lords || RET=1
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse ni || RET=1

# New UK Parliament Written Answers database
cd ~/parlparse/
~/.venv/bin/python wrans-2014/parse.py --house commons --out ~/parldata/scrapedxml/wrans/ --members ~/parlparse/members/all-members-2010.xml
~/.venv/bin/python wrans-2014/parse.py --house lords --out ~/parldata/scrapedxml/lordswrans/ --members ~/parlparse/members/peers-ucl.xml

# Public Bill Committee transcripts
cd ~/parlparse/pyscraper/standing
./parse.py $4

# Scottish Parliament:
# Disabled as currently not working
# cd ~/parlparse/pyscraper/sp
# ./parse-official-reports-new.py --from=$FROMDATE --to=$TODATE || RET=1

# Return error code
exit $RET
