#!/bin/bash

# Scraping between two dates

FROMDATE=$1
LORDFROMDATE=$2
TODATE=$3
RET=0
# $4 is extra flags to pass through
# echo "updatedaterange from $1/$2 to $3"

# Run XML-generating scraper from Public Whip, getting new files from network
cd ~/parlparse/pyscraper
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE scrape ni || RET=1
./unpack_hansard_zips.py

# XXX Should vary based upon weekly/daily-ness; and be more attuned than a year
# The form for browsing official reports by date is here, and it's
# horrible to scrape:
#   http://www.scottish.parliament.uk/parliamentarybusiness/39977.aspx
# So for the moment, just run the daily check whatever the parameters
# given passed to this script are.

# Senedd
wa/scrape.py

# Scottish Parliament
cd ~/parlparse
python -m pyscraper.sp_2024 debates --download --start-date $FROMDATE --end-date $TODATE


# Return error code
exit $RET
