#!/bin/bash

# Parsing

FROMDATE=$1
LORDFROMDATE=$2
TODATE=$3
RET=0
# $4 is extra flags to pass through
# echo "updatedaterange from $1/$2 to $3"

cd ~/parlparse/pyscraper
# UK parser, to convert fetched XML into our XML format
./process_hansard.py
# NI parser, to convert fetched JSON into our XML format
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse ni || RET=1

# New UK Parliament Written Answers and Statements database
cd ~/parlparse/
wrans-2014/parse.py --house commons --type answers --out ~/parldata/scrapedxml/wrans/ --members ~/parlparse/members/people.json
wrans-2014/parse.py --house commons --type statements --out ~/parldata/scrapedxml/wms/ --members ~/parlparse/members/people.json
wrans-2014/parse.py --house lords --type answers --out ~/parldata/scrapedxml/lordswrans/ --members ~/parlparse/members/people.json
wrans-2014/parse.py --house lords --type statements --out ~/parldata/scrapedxml/lordswms/ --members ~/parlparse/members/people.json

# Scottish Parliament:
cd ~/parlparse/pyscraper/sp
./parse-official-reports-new.py --from=$FROMDATE --to=$TODATE || RET=1

# London Assembly questions
cd ~/parlparse/london-mayors-questions
./questions.py fetch-unknown-questions --last-week fetch-unstored refresh-unanswered build-xml --outdir ~/parldata/scrapedxml/london-mayors-questions

# Return error code
exit $RET
