#!/bin/bash

# Scraping between two dates

FROMDATE=$1
LORDFROMDATE=$2
TODATE=$3
RET=0
# $4 is extra flags to pass through
# echo "updatedaterange from $1/$2 to $3"

# Run XML-generating scraper from Public Whip, getting new files from network
cd ~/parlparse/pyscraper
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE scrape debates wrans westminhall wms ni || RET=1
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE scrape standing || RET=1
./lazyrunall.py $4 --from=$LORDFROMDATE --to=$TODATE scrape lords || RET=1

# XXX Should vary based upon weekly/daily-ness; and be more attuned than a year
# The form for browsing official reports by date is here, and it's
# horrible to scrape:
#   http://www.scottish.parliament.uk/parliamentarybusiness/39977.aspx
# So for the moment, just run the daily check whatever the parameters
# given passed to this script are.
cd ~/parlparse/pyscraper/sp
./get-official-reports-new.py --daily --quiet

# Currently totally unused
#cd ~/parlparse/pyscraper/future
#./get_future_business_and_calendar.py --quiet

# Return error code
exit $RET
