#!/bin/bash

# Commons update

FROMDATE=$1
TODATE=$2
RET=0
# $3 is extra flags to pass through
# echo "updatedaterange from $1 to $2"

# Run XML-generating scraper from Public Whip, getting new files from network
# and parsing the written answers and debates.
cd ~/parlparse/pyscraper
# We do these on separate lines, so if one fails, others still run
./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse debates || RET=1
./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse wrans || RET=1
./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse westminhall || RET=1
./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse wms || RET=1

# Yeah, it's not as fully featured as the UK Parliament one. But it should work :)
cd ~/parlparse/pyscraper/ni
./parse.py $3

# Public Bill Committee transcripts
cd ~/parlparse/pyscraper/standing
./parse.py $3

# Return error code
exit $RET
