#!/bin/bash
#set -x  # for debugging, prints each line before executing it

# Jobs that need running weekly
# Currently empty, and moved to dataupdate

source ~/parlparse/scripts/consts

#cd ~
#rm -f ~/parldatazips/parldata.zip
#find parldata | egrep -v "tmp/|\.svn|\.zip" | zip -q ~/parldatazips/parldata.zip -@


